In [9]:
with open("my_text.txt", "w") as f:
 f.write("I love to code in Python")

In [10]:
with open("my_text.txt", "r") as f:
    text_1 = f.readlines()
    print(text_1)

['I love to code in Python']

In [12]:
data_dick= { 'books ' :12,  'articles': 100, 'subjects': ['maths' , 'programming' , 'data science'] }
import json
j_String= json.dumps(data_dick)
print(j_String)

{"books ": 12, "articles": 100, "subjects": ["maths", "programming", "data science"]}

In [13]:
dick_convert=json.loads(j_String)
print(dick_convert)

{'books ': 12, 'articles': 100, 'subjects': ['maths', 'programming', 'data science']}

In [8]:

import pandas as pd
customer_id = pd.read_csv('Customers.csv')
customer_id.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,7/26/2021,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,6/24/2021,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,4/5/2020,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,11/29/2020,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,4/22/2022,http://merritt.com/

In [19]:
import pandas as pd
df= pd.read_excel('gad.xlsx')
df.head()

,SN,NAME,ELECTORAL AREA,POLLING STATION,POSITION,CONTACT
0,1,"TAGBODZA, JAMES DELASE",VE- DEME,TRAD.COUN. VE-DEME,CHAIRMAN,593144000
1,2,"TAGBODZA, SAMPSON WOELINAM",VE- DEME,E.P. PRIM. SCH. DEME,YOUTH ORGANISER,599654276
2,3,WALTER DOKPUI,VE- DEME,L.A. JHS GBORDOME,COORDINATOR,241838021
3,4,"TENE, EUNICE",VE- DEME,E.P. PRIM. SCH. HOEME,SECRETARY,532526326
4,5,"DOKPUIE, GODWIN",VE- DEME,L.A. JHS GBORDOME,YOUTH ORGANISER,241028428

In [20]:
import numpy as np
a= np.array(32)
print(a)

32

In [23]:
b=np.array([10,20,30,40,50])
b.ndim

1

In [27]:
c= np.zeros((2,4))

print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]